/* jshint esversion:6*/
const data = {
  defaultPointsDisplayed: [
    "Tarnos",
    "Boucau",
    "Bayonne",
    "Biarritz",
    "Anglet",
    "Bidart",
    "Bassussary",
  ],
  lines: [
    { start: "Mora", end: "Tarnos", difficulty: 0, time: 10 },
    { start: "Mora", end: "Forges", difficulty: 0, time: 8 },
    { start: "Mora", end: "Boucau", difficulty: 0, time: 10 },
    { start: "Tarnos", end: "Humere", difficulty: 0, time: 5 },
    { start: "Tarnos", end: "Forges", difficulty: 0, time: 14 },
    { start: "Tarnos", end: "Matignon", difficulty: 0, time: 7 },
    { start: "Tarnos", end: "Boucau", difficulty: 0, time: 15 },
    { start: "Humere", end: "Matignon", difficulty: 0, time: 6 },
    { start: "Humere", end: "Seque", difficulty: 0, time: 12 },
    { start: "Forges", end: "Boucau", difficulty: 0, time: 5 },
    { start: "Matignon", end: "Boucau", difficulty: 0, time: 11 },
    { start: "Matignon", end: "Habas", difficulty: 0, time: 12 },
    { start: "LaBarre", end: "Blancpignon", difficulty: 0, time: 11 },
    { start: "LaBarre", end: "ChambreAmour", difficulty: 0, time: 15 },
    { start: "Boucau", end: "LaBarre", difficulty: 0, time: 17, className:"bateau" },
    { start: "Boucau", end: "Blancpignon", difficulty: 0, time: 16, className:"bateau" },
    { start: "Boucau", end: "Habas", difficulty: 0, time: 14 },
    { start: "Boucau", end: "Forum", difficulty: 0, time: 20 },
    { start: "Boucau", end: "Bayonne", difficulty: 0, time: 18 },
    { start: "Blancpignon", end: "ChambreAmour", difficulty: 0, time: 13 },
    { start: "Blancpignon", end: "Forum", difficulty: 0, time: 11 },
    { start: "Blancpignon", end: "5cantons", difficulty: 0, time: 11 },
    
    { start: "Blancpignon", end: "Anglet", difficulty: 0, time: 12 },
    { start: "Seque", end: "PlaceGascons", difficulty: 0, time: 12 },
    { start: "Seque", end: "Arrousets", difficulty: 0, time: 10 },
    
    { start: "Habas", end: "Forum", difficulty: -1, time: 10, times: {easy:7, hard:13} },
    { start: "Habas", end: "PlaceGascons", difficulty: 0, time: 7 },
    { start: "Habas", end: "Bayonne", difficulty: -1, time: 12, times: {easy:9, hard:14} },
    { start: "ChambreAmour", end: "5cantons", difficulty: 0, time: 7 },
    { start: "ChambreAmour", end: "SaintCharles", difficulty: 0, time: 9 },
    { start: "ChambreAmour", end: "Biarritz", difficulty: 0, time: 13 },
    { start: "Forum", end: "5cantons", difficulty: 0, time: 14 },
    { start: "Forum", end: "Anglet", difficulty: 0, time: 10 },
    { start: "Forum", end: "Marracq", difficulty: 0, time: 10 },
    { start: "5cantons", end: "SaintCharles", difficulty: 0, time: 9 },
    { start: "5cantons", end: "Anglet", difficulty: 0, time: 9 },
    { start: "5cantons", end: "Aeroport", difficulty: 0, time: 12 },
    { start: "PlaceGascons", end: "Arrousets", difficulty: 0, time: 10 },
    { start: "PlaceGascons", end: "Bayonne", difficulty: 0, time: 9 },
    { start: "PlaceGascons", end: "SaintFrederic", difficulty: 0, time: 7 },
    { start: "Arrousets", end: "SaintFrederic", difficulty: 0, time: 9 },
    { start: "Bayonne", end: "Forum", difficulty: 0, time: 9 },
    { start: "Bayonne", end: "Mousserolles", difficulty: 0, time: 6 },
    
    { start: "Bayonne", end: "Anglet", difficulty: 0, time: 14 },
    { start: "Bayonne", end: "Marracq", difficulty: 0, time: 8 },
    { start: "SaintCharles", end: "Biarritz", difficulty: 0, time: 8 },
    { start: "SaintCharles", end: "Aeroport", difficulty: 0, time: 10 },
    { start: "SaintCharles", end: "Iraty", difficulty: 0, time: 16 },
    { start: "SaintFrederic", end: "Bayonne", difficulty: 0, time: 11 },
    { start: "SaintFrederic", end: "Mousserolles", difficulty: 0, time: 6 },
    { start: "SaintFrederic", end: "EuroFret", difficulty: 0, time: 18 },
    { start: "Mousserolles", end: "Anglet", difficulty: 0, time: 13 },
    { start: "Mousserolles", end: "Marracq", difficulty: 0, time: 7 },
    { start: "Mousserolles", end: "Mendixta", difficulty: 0, time: 12 },
    { start: "EuroFret", end: "Mendixta", difficulty: 0, time: 16 },
    { start: "Biarritz", end: "Aeroport", difficulty: 0, time: 9 },
    { start: "Biarritz", end: "Iraty", difficulty: 0, time: 11 },
    { start: "Biarritz", end: "Milady", difficulty: 0, time: 11 },
    { start: "Anglet", end: "Biarritz", difficulty: 0, time: 18 },
    { start: "Anglet", end: "Aeroport", difficulty: 0, time: 12 },
    { start: "Anglet", end: "Technocite", difficulty: 0, time: 12 },
    { start: "Marracq", end: "Anglet", difficulty: 0, time: 11 },
    { start: "Marracq", end: "Technocite", difficulty: 0, time: 8 },
    { start: "Aeroport", end: "Technocite", difficulty: 0, time: 20 },
    { start: "Aeroport", end: "Iraty", difficulty: 0, time: 9 },
    { start: "Technocite", end: "Iraty", difficulty: 0, time: 22 },
    { start: "Technocite", end: "Bassussary", difficulty: 0, time: 10 },
    { start: "Technocite", end: "LoreLanda", difficulty: 0, time: 19 },
    { start: "Technocite", end: "Arcangues", difficulty: 0, time: 15 },
    { start: "Iraty", end: "Milady", difficulty: 0, time: 9 },
    { start: "Iraty", end: "Izarbel", difficulty: 0, time: 11 },
    { start: "Iraty", end: "LoreLanda", difficulty: 0, time: 11 },
    { start: "Iraty", end: "Ilbarritz", difficulty: 0, time: 14 },
    { start: "Milady", end: "Ilbarritz", difficulty: 0, time: 6 },
    { start: "Milady", end: "Bidart", difficulty: 0, time: 14 },
    { start: "Bassussary", end: "Iraty", difficulty: 0, time: 15 },
    { start: "Bassussary", end: "Arcangues", difficulty: 0, time: 7 },
    { start: "Izarbel", end: "LoreLanda", difficulty: 0, time: 4 },
    { start: "Izarbel", end: "Uhabia", difficulty: 0, time: 13 },
    { start: "LoreLanda", end: "Arcangues", difficulty: 0, time: 11 },
    { start: "LoreLanda", end: "Arbonne", difficulty: 0, time: 6 },
    { start: "LoreLanda", end: "Uhabia", difficulty: 0, time: 14 },
    { start: "Ilbarritz", end: "Uhabia", difficulty: 0, time: 9 },
    { start: "Ilbarritz", end: "Bidart", difficulty: 0, time: 8 },
    { start: "Arcangues", end: "Arbonne", difficulty: -1, time: 18, times: {easy:16, hard:19} },
    { start: "Arbonne", end: "Uhabia", difficulty: 0, time: 9 },
    { start: "Bidart", end: "Uhabia", difficulty: 0, time: 12 },
    
  ],
  points: {
    "Mora": {label:"Square Mora - L'Océan", x:420, y:33},
    "Tarnos": {label:"Tarnos", x:532, y:74},
    "Humere": {label:"La Humère", x:591, y:116},
    "Forges": {label:"Forges", x:392, y:117},
    "Matignon": {label:"Matignon - Castillon", x:556, y:138},
    "LaBarre": {label:"La Barre - Chiberta", x:308, y:143},
    "Boucau": {label:"Boucau", x:423, y:147},
    "Blancpignon": {label:"Blancpignon - Montbrun", x:375, y:197},
    "Seque": {label:"Séqué - Baudonne", x:626, y:202},
    "Habas": {label:"Habas", x:521, y:226},
    "ChambreAmour": {label:"Chambre d'Amour", x:249, y:231},
    "Forum": {label:"Forum - CPAM - Jorlis", x:403, y:253},
    "5cantons": {label:"Cinq Cantons - Chassin", x:318, y:257},
    "PlaceGascons": {label:"Place des Gascons", x:526, y:262},
    "Arrousets": {label:"Arrousets", x:621, y:279},
    "Bayonne": {label:"Bayonne", x:469, y:301},
    "SaintCharles": {label:"Saint Charles - Larochefoucauld", x:241, y:314},
    "SaintFrederic": {label:"Zone Saint Frédéric", x:554, y:327},
    "Mousserolles": {label:"Glain - Mousserolles", x:503, y:330},
    "EuroFret": {label:"Centre Euro de Fret", x:619, y:341},
    "Biarritz": {label:"Biarritz", x:163, y:356},
    "Anglet": {label:"Anglet", x:336, y:358},
    "Marracq": {label:"Hôpitaux - Marracq", x:459, y:360},
    "Aeroport": {label:"Aéroport - Aguiléra", x:257, y:407},
    "Mendixta": {label:"Ourourspoure - Mendixta - Loste", x:605, y:416},
    "Technocite": {label:"Technocité - Sutar - Aritxague", x:402, y:432},
    "Iraty": {label:"La Négresse - Iraty", x:203, y:489},
    "Milady": {label:"Cité de l'Océan - Milady", x:85, y:492},
    "Bassussary": {label:"Bassussary", x:418, y:517},
    "Izarbel": {label:"Technopôle Izarbel", x:212, y:535},
    "LoreLanda": {label:"Pôle Lore Landa", x:269, y:534},
    "Ilbarritz": {label:"lbarritz - Burruntz", x:78, y:566},
    "Arcangues": {label:"Arcangues", x:540, y:570},
    "Arbonne": {label:"Arbonne", x:350, y:578},
    "Uhabia": {label:"Uhabia - Bassilour", x:201, y:609},
    "Bidart": {label:"Bidart", x:14, y:619},

  },
};