const data = {
  defaultPointsDisplayed: [
    "Place de l’Étoile",
    "Montmartre",
    "République",
    "Place d’Italie",
    "Les Halles – Rivoli",
    "Gare Montparnasse",
    "Maison de la Radio",
    "Nation",
  ],
  lines: [{
      start: "Convention",
      end: "Invalides",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
    {
      start: "Convention",
      end: "Porte de Versailles",
      difficulty: 0,
      displayMin: false,
      time: 3,
      align: "top",
    },
    {
      start: "Convention",
      end: "Gare Montparnasse",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Convention",
      end: "Porte d’Orléans",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Convention",
      end: "Porte de Saint-Cloud",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Porte de Saint-Cloud",
      end: "Marcel Sembat",
      difficulty: 0,
      displayMin: false,
      time: 5,
      align: "top",
    },
    {
      start: "Porte de Saint-Cloud",
      end: "Mairie de Saint-Cloud",
      difficulty: -1,
      displayMin: true,
      time: 17,
      times: { hard: 18, easy: 16 },
      align: "top",
    },
    {
      start: "Pont de Sèvres",
      end: "Mairie de Saint-Cloud",
      difficulty: -1,
      displayMin: true,
      time: 15,
      times: { hard: 17, easy: 14 },
      align: "top",
    },
    {
      start: "Pont de Sèvres",
      end: "Mairie de Sèvres",
      difficulty: 1,
      displayMin: false,
      time: 6,
      times: { hard: 5, easy: 7 },
      align: "top",
    },
    {
      start: "Mairie de Sèvres",
      end: "Chaville",
      difficulty: 1,
      displayMin: true,
      time: 9,
      times: { hard: 10, easy: 8 },
      align: "top",
    },
    {
      start: "↓ Vélizy-Villacoublay",
      end: "Chaville",
      difficulty: 1,
      displayMin: true,
      time: 18,
      times: { hard: 21, easy: 15 },
      align: "top",
    },
    {
      start: "Chaville",
      end: "Viroflay",
      difficulty: 1,
      displayMin: false,
      time: 8,
      times: { hard: 9, easy: 7 },
      align: "top",
    },
    {
      start: "Pont de Sèvres",
      end: "Résistance — Île Saint-Germain",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Pont de Sèvres",
      end: "Marcel Sembat",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Marcel Sembat",
      end: "Mairie de Saint-Cloud",
      difficulty: -1,
      displayMin: true,
      time: 13,
      times: { hard: 14, easy: 12 },
      align: "top",
    },
    {
      start: "Suresnes",
      end: "Mairie de Saint-Cloud",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "Issy – Val-de-Seine",
      end: "Marcel Sembat",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Hôpital Corentin-Celton",
      end: "Porte de Versailles",
      difficulty: 0,
      displayMin: false,
      time: 4,
      align: "top",
    },
    {
      start: "Hôpital Corentin-Celton",
      end: "Mairie de Vanves",
      difficulty: 1,
      displayMin: false,
      time: 6,
      times: { hard: 7, easy: 5 },
      align: "top",
    },
    {
      start: "Mairie de Vanves",
      end: "Porte de Versailles",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Convention",
      end: "Maison de la Radio",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Convention",
      end: "Tour Eiffel",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "Gare Montparnasse",
      end: "Invalides",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Gare Montparnasse",
      end: "Saint-Michel – Saint-Germain",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Gare Montparnasse",
      end: "Denfert-Rochereau",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Gare Montparnasse",
      end: "Porte d’Orléans",
      difficulty: 0,
      displayMin: true,
      time: 16,
      align: "top",
    },
    {
      start: "Gare Saint-Lazare",
      end: "Porte de Clichy",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "bottom",
    },
    {
      start: "Gare Saint-Lazare",
      end: "Montmartre",
      difficulty: -1,
      displayMin: false,
      time: 11,
      times: { easy: 10, hard: 12 },
      align: null,
    },
    {
      start: "Gare Saint-Lazare",
      end: "Gare du Nord",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Gare Saint-Lazare",
      end: "Bourse",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Gare Saint-Lazare",
      end: "Place de la Concorde",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Gare Saint-Lazare",
      end: "Place de l’Étoile",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Gare de Lyon",
      end: "Nation",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "bottom",
    },
    {
      start: "Gare de Lyon",
      end: "Porte de Bercy",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "bottom",
    },
    {
      start: "Gare de Lyon",
      end: "Place d’Italie",
      difficulty: 1,
      displayMin: true,
      time: 9,
      times: { hard: 10, easy: 8 },
      align: null,
    },
    {
      start: "Invalides",
      end: "Saint-Michel – Saint-Germain",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "bottom",
    },
    {
      start: "Gare de Lyon",
      end: "Saint-Michel – Saint-Germain",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "bottom",
    },
    {
      start: "Bastille",
      end: "Saint-Michel – Saint-Germain",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "bottom",
    },
    {
      start: "Gare du Nord",
      end: "Porte de la Chapelle",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Gare du Nord",
      end: "La Villette",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
    {
      start: "Gare du Nord",
      end: "Belleville – Pyrénées",
      difficulty: 1,
      displayMin: true,
      time: 13,
      times: { hard: 14, easy: 12 },
      align: null,
    },
    {
      start: "Gare du Nord",
      end: "République",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "bottom",
    },
    {
      start: "Gare du Nord",
      end: "Bourse",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Gare du Nord",
      end: "Montmartre",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { easy: 9, hard: 12 },
      align: null,
    },
    {
      start: "Invalides",
      end: "Place de la Concorde",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Invalides",
      end: "Les Halles – Rivoli",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "bottom",
    },
    {
      start: "Invalides",
      end: "Tour Eiffel",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "bottom",
    },
    {
      start: "Saint-Michel – Saint-Germain",
      end: "Les Halles – Rivoli",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Saint-Michel – Saint-Germain",
      end: "Place d’Italie",
      difficulty: 1,
      displayMin: false,
      time: 10,
      times: { hard: 11, easy: 9 },
      align: null,
    },
    {
      start: "Saint-Michel – Saint-Germain",
      end: "Place de la Concorde",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "La Villette",
      end: "Porte des Lilas",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 11, easy: 9 },
      align: null,
    },
    {
      start: "Porte de Bagnolet",
      end: "Porte des Lilas",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { hard: 11, easy: 9 },
      align: null,
    },
    {
      start: "Belleville – Pyrénées",
      end: "Porte des Lilas",
      difficulty: -1,
      displayMin: false,
      time: 6,
      times: { hard: 8, easy: 5 },
      align: null,
    },
    {
      start: "Croix de Chavaux",
      end: "Mairie des Lilas",
      difficulty: -1,
      displayMin: true,
      time: 12,
      times: { hard: 14, easy: 10 },
      align: null,
    },
    {
      start: "Croix de Chavaux",
      end: "Mairie de Romainville",
      difficulty: -1,
      displayMin: true,
      time: 13,
      times: { hard: 15, easy: 12 },
      align: null,
    },
    {
      start: "Hôpital André-Grégoire – La Boissière",
      end: "Mairie de Romainville",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: null,
    },
    {
      start: "Croix de Chavaux",
      end: "Hôpital André-Grégoire – La Boissière",
      difficulty: -1,
      displayMin: true,
      time: 15,
      times: { hard: 17, easy: 14 },
      align: null,
    },
    {
      start: "Mairie de Rosny",
      end: "Hôpital André-Grégoire – La Boissière",
      difficulty: -1,
      displayMin: true,
      time: 16,
      times: { hard: 18, easy: 15 },
      align: null,
    },
    {
      start: "Mairie de Rosny",
      end: "Murs à Pêches – Les Ruffins",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { hard: 12, easy: 10 },
      align: null,
    },
    {
      start: "Mairie de Rosny",
      end: "Val de Fontenay",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Neuilly-Plaisance →",
      end: "Val de Fontenay",
      difficulty: 0,
      displayMin: true,
      time: 10,
      times: { hard: 8, easy: 12 },
      align: "top",
    },
    {
      start: "Mairie de Rosny",
      end: "Neuilly-Plaisance →",
      difficulty: 0,
      displayMin: true,
      time: 10,
      times: { hard: 9, easy: 11 },
      align: "top",
    },
    {
      start: "Le Perreux-sur-Marne",
      end: "Neuilly-Plaisance →",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "bottom",
    },
    {
      start: "Le Perreux-sur-Marne",
      end: "Bry-sur-Marne →",
      difficulty: 0,
      displayMin: false,
      time: 6,
      align: "bottom",
    },
    {
      start: "Mairie de Champigny-sur-Marne",
      end: "Bry-sur-Marne →",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "Mairie de Champigny-sur-Marne",
      end: "Pont de Joinville",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "bottom",
    },
    {
      start: "Mairie de Nogent-sur-Marne",
      end: "Bry-sur-Marne →",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "bottom",
    },
    {
      start: "Le Perreux-sur-Marne",
      end: "Mairie de Nogent-sur-Marne",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Le Perreux-sur-Marne",
      end: "Val de Fontenay",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Mairie de Fontenay-sous-Bois",
      end: "Val de Fontenay",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Mairie de Nogent-sur-Marne",
      end: "Val de Fontenay",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Croix de Chavaux",
      end: "Murs à Pêches – Les Ruffins",
      difficulty: -1,
      displayMin: true,
      time: 12,
      times: { hard: 14, easy: 10 },
      align: null,
    },
    {
      start: "Mairie de Fontenay-sous-Bois",
      end: "Murs à Pêches – Les Ruffins",
      difficulty: -1,
      displayMin: true,
      time: 13,
      times: { hard: 16, easy: 10 },
      align: null,
    },
    {
      start: "Mairie des Lilas",
      end: "Porte des Lilas",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: null,
    },
    {
      start: "Mairie de Romainville",
      end: "Mairie des Lilas",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: null,
    },
    {
      start: "La Villette",
      end: "Belleville – Pyrénées",
      difficulty: 1,
      displayMin: true,
      time: 12,
      times: { hard: 14, easy: 10 },
      align: null,
    },
    {
      start: "La Villette",
      end: "Porte de la Chapelle",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "La Villette",
      end: "Mairie de Pantin",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Mairie de Bobigny",
      end: "Mairie de Pantin",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "Mairie de Drancy",
      end: "Mairie de Pantin",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Mairie de Bobigny",
      end: "Mairie de Drancy",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Hôpital Jean-Verdier",
      end: "Mairie de Drancy",
      difficulty: 0,
      displayMin: true,
      time: 16,
      align: "top",
    },
    {
      start: "Hôpital Jean-Verdier",
      end: "Mairie de Bobigny",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Hôpital Jean-Verdier",
      end: "Gare de Bondy",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Mairie de Bobigny",
      end: "Gare de Bondy",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "Mairie de Bobigny",
      end: "Noisy-le-Sec",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Bobigny – Pantin – Raymond Queneau",
      end: "Noisy-le-Sec",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Bobigny – Pantin – Raymond Queneau",
      end: "Mairie de Pantin",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Mairie de Rosny",
      end: "Gare de Bondy",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Mairie de Rosny",
      end: "Villemomble",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Villemomble",
      end: "Gare de Bondy",
      difficulty: 1,
      displayMin: true,
      time: 11,
      times: { hard: 12, easy: 10 },
      align: "top",
    },
    {
      start: "Villemomble",
      end: "Hôpital Jean-Verdier",
      difficulty: 1,
      displayMin: true,
      time: 18,
      times: { hard: 22, easy: 16 },
      align: "top",
    },
    {
      start: "Noisy-le-Sec",
      end: "Gare de Bondy",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 11, easy: 8 },
      align: "top",
    },
    {
      start: "Hôpital André-Grégoire – La Boissière",
      end: "Gare de Bondy",
      difficulty: 1,
      displayMin: true,
      time: 21,
      times: { hard: 24, easy: 18 },
      align: "top",
    },
    {
      start: "Hôpital André-Grégoire – La Boissière",
      end: "Murs à Pêches – Les Ruffins",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Bobigny – Pantin – Raymond Queneau",
      end: "Mairie de Romainville",
      difficulty: 1,
      displayMin: false,
      time: 9,
      times: { hard: 11, easy: 7 },
      align: "top",
    },
    {
      start: "Bobigny – Pantin – Raymond Queneau",
      end: "Mairie des Lilas",
      difficulty: 1,
      displayMin: false,
      time: 10,
      times: { hard: 12, easy: 8 },
      align: "top",
    },
    {
      start: "Mairie de Pantin",
      end: "Mairie des Lilas",
      difficulty: 1,
      displayMin: true,
      time: 12,
      times: { hard: 15, easy: 10 },
      align: "top",
    },
    {
      start: "Mairie de Romainville",
      end: "Noisy-le-Sec",
      difficulty: 1,
      displayMin: false,
      time: 10,
      times: { hard: 11, easy: 8 },
      align: "top",
    },
    {
      start: "Mairie de Rosny",
      end: "Noisy-le-Sec",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
    {
      start: "Maison de la Radio",
      end: "Porte Maillot",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "La Défense",
      end: "Porte Maillot",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Maison de la Radio",
      end: "Place de l’Alma",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Invalides",
      end: "Place de l’Alma",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Maison de la Radio",
      end: "Tour Eiffel",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "bottom",
    },
    {
      start: "Maison de la Radio",
      end: "Porte de Saint-Cloud",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Montmartre",
      end: "Porte de Clichy",
      difficulty: 1,
      displayMin: true,
      time: 14,
      times: { easy: 13, hard: 16 },
      align: null,
    },
    {
      start: "Montmartre",
      end: "Porte de la Chapelle",
      difficulty: 1,
      displayMin: true,
      time: 15,
      times: { easy: 14, hard: 16 },
      align: null,
    },
    {
      start: "Nation",
      end: "Porte de Bercy",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Nation",
      end: "Bastille",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "bottom",
    },
    {
      start: "Nation",
      end: "Père Lachaise",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Nation",
      end: "Porte de Bagnolet",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
    {
      start: "Les Halles – Rivoli",
      end: "République",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "bottom",
    },
    {
      start: "Les Halles – Rivoli",
      end: "Bourse",
      difficulty: 0,
      displayMin: false,
      time: 6,
      align: "top",
    },
    {
      start: "Les Halles – Rivoli",
      end: "Bastille",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Saint-Michel – Saint-Germain",
      end: "Denfert-Rochereau",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: {hard: 11, easy: 9},
      align: "top",
    },
    {
      start: "Place d’Italie",
      end: "Denfert-Rochereau",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Les Halles – Rivoli",
      end: "Place de la Concorde",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Belleville – Pyrénées",
      end: "Porte de Bagnolet",
      difficulty: -1,
      displayMin: true,
      time: 12,
      times: { easy: 10, hard: 14 },
      align: null,
    },
    {
      start: "Belleville – Pyrénées",
      end: "Père Lachaise",
      difficulty: -1,
      displayMin: false,
      time: 6,
      times: { easy: 5, hard: 8 },
      align: null,
    },
    {
      start: "République",
      end: "Père Lachaise",
      difficulty: 1,
      displayMin: false,
      time: 7,
      times: { easy: 6, hard: 8 },
      align: null,
    },
    {
      start: "Belleville – Pyrénées",
      end: "République",
      difficulty: -1,
      displayMin: true,
      time: 9,
      times: { easy: 8, hard: 10 },
      align: null,
    },
    {
      start: "Denfert-Rochereau",
      end: "Porte d’Orléans",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Place d’Italie",
      end: "Porte de Bercy",
      difficulty: -1,
      displayMin: true,
      time: 14,
      times: { hard: 16, easy: 12 },
      align: null,
    },
    {
      start: "Place d’Italie",
      end: "Porte d’Orléans",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Place de l’Étoile",
      end: "Porte de Clichy",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
    {
      start: "Place de l’Étoile",
      end: "Place de la Concorde",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Place de l’Alma",
      end: "Tour Eiffel",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "bottom",
    },
    {
      start: "Place de l’Alma",
      end: "Place de l’Étoile",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "bottom",
    },
    {
      start: "Place de l’Alma",
      end: "Place de la Concorde",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Place de l’Étoile",
      end: "Porte Maillot",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Bastille",
      end: "République",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Voltaire",
      end: "Père Lachaise",
      difficulty: 0,
      displayMin: false,
      time: 4,
      align: "top",
    },
    {
      start: "Bastille",
      end: "Voltaire",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Nation",
      end: "Voltaire",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "bottom",
    },
    {
      start: "République",
      end: "Voltaire",
      difficulty: 0,
      displayMin: false,
      time: 7,
      align: "bottom",
    },
    {
      start: "Bastille",
      end: "Gare de Lyon",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "bottom",
    },
    {
      start: "Bourse",
      end: "République",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Place de la Concorde",
      end: "Bourse",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Porte Maillot",
      end: "Porte de Clichy",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
    {
      start: "Porte de Passy",
      end: "Porte de Saint-Cloud",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Porte Maillot",
      end: "Porte de Passy",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "Porte Maillot",
      end: "Hippodrome de Longchamp",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Porte de Saint-Cloud",
      end: "Hippodrome de Longchamp",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Porte de Versailles",
      end: "Porte de Saint-Cloud",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "bottom",
    },
    {
      start: "Porte d’Orléans",
      end: "Porte de Versailles",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 11, easy: 8 },
      align: "top",
    },
    {
      start: "Porte d’Orléans",
      end: "Porte d’Italie",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Place d’Italie",
      end: "Porte d’Italie",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Porte d’Italie",
      end: "Porte de Bercy",
      difficulty: 1,
      displayMin: true,
      time: 13,
      times: { hard: 15, easy: 11 },
      align: null,
    },
    {
      start: "Porte d’Italie",
      end: "Villejuif",
      difficulty: -1,
      displayMin: true,
      time: 13,
      times: { hard: 15, easy: 11 },
      align: null,
    },
    {
      start: "Porte d’Italie",
      end: "Ivry-sur-Seine",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { hard: 12, easy: 9 },
      align: null,
    },
    {
      start: "Porte d’Italie",
      end: "CHU du Kremlin-Bicêtre",
      difficulty: 1,
      displayMin: false,
      time: 7,
      times: { hard: 7, easy: 6 },
      align: null,
    },
    {
      start: "Arcueil",
      end: "CHU du Kremlin-Bicêtre",
      difficulty: -1,
      displayMin: true,
      time: 8,
      times: { hard: 9, easy: 7 },
      align: null,
    },
    {
      start: "Arcueil",
      end: "Cachan",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: 'bottom',
    },
    {
      start: "Arcueil",
      end: "Châtillon Montrouge",
      difficulty: -1,
      displayMin: true,
      time: 14,
      times: { hard: 16, easy: 12 },
      align: null,
    },
    {
      start: "Mairie de Châtillon",
      end: "Châtillon Montrouge",
      difficulty: 1,
      displayMin: false,
      time: 8,
      times: { hard: 9, easy: 7 },
      align: null,
    },
    {
      start: "Clamart",
      end: "Mairie de Châtillon",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: 'top',
    },
    {
      start: "↓ Fontenay-aux-Roses",
      end: "Mairie de Châtillon",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: 'bottom',
    },
    {
      start: "Mairie de Vanves",
      end: "Châtillon Montrouge",
      difficulty: 1,
      displayMin: false,
      time: 7,
      times: { hard: 8, easy: 6 },
      align: null,
    },
    {
      start: "↓ Fontenay-aux-Roses",
      end: "Châtillon Montrouge",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: 'bottom',
    },
    {
      start: "↓ Fontenay-aux-Roses",
      end: "Bagneux",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: 'bottom',
    },
    {
      start: "Bagneux",
      end: "Cachan",
      difficulty: -1,
      displayMin: false,
      time: 12,
      times: { hard: 14, easy: 10 },
      align: null,
    },
    {
      start: "Bagneux",
      end: "Châtillon Montrouge",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: 'top',
    },
    {
      start: "Arcueil",
      end: "Porte d’Orléans",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { hard: 11, easy: 8 },
      align: null,
    },
    {
      start: "Porte d’Orléans",
      end: "Châtillon Montrouge",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: null,
    },
    {
      start: "Porte de Bagnolet",
      end: "Père Lachaise",
      difficulty: -1,
      displayMin: false,
      time: 9,
      times: { hard: 10, easy: 8 },
      align: null,
    },
    {
      start: "Porte de Clichy",
      end: "Porte de Saint-Ouen",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Porte de Saint-Ouen",
      end: "Porte de la Chapelle",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Croix de Chavaux",
      end: "Nation",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Croix de Chavaux",
      end: "Porte de Bagnolet",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Croix de Chavaux",
      end: "Château de Vincennes",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Château de Vincennes",
      end: "Nation",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Croix de Chavaux",
      end: "Mairie de Fontenay-sous-Bois",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Mairie de Nogent-sur-Marne",
      end: "Mairie de Fontenay-sous-Bois",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Château de Vincennes",
      end: "Mairie de Fontenay-sous-Bois",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Porte Dorée",
      end: "Château de Vincennes",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Porte Dorée",
      end: "Nation",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Porte Dorée",
      end: "Porte de Bercy",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Épinay-sur-Seine",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "bottom",
    },
    {
      start: "Villetaneuse",
      end: "Stains",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "bottom",
    },
    {
      start: "Saint-Denis",
      end: "Stains",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "bottom",
    },
    {
      start: "Le Bourget",
      end: "Stains",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "Le Bourget",
      end: "Le Blanc-Mesnil",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Mairie de Drancy",
      end: "Le Blanc-Mesnil",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Mairie d’Aulnay-sous-Bois",
      end: "Le Blanc-Mesnil",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Mairie de Drancy",
      end: "Mairie d’Aulnay-sous-Bois",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Hôpital Jean-Verdier",
      end: "Mairie d’Aulnay-sous-Bois",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Villepinte ↗",
      end: "Mairie d’Aulnay-sous-Bois",
      difficulty: -1,
      displayMin: true,
      time: 17,
      times: {hard: 19, easy: 16},
      align: "top",
    },
    {
      start: "Villepinte ↗",
      end: "Le Bourget",
      difficulty: -1,
      displayMin: true,
      time: 39,
      times: {hard: 41, easy: 37},
      align: "top",
    },
    {
      start: "Parc de La Courneuve",
      end: "Stains",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "bottom",
    },
    {
      start: "Villetaneuse",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 16,
      align: "bottm",
    },
    {
      start: "Épinay-sur-Seine",
      end: "Villetaneuse",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Épinay-sur-Seine",
      end: "Mairie de Gennevilliers",
      difficulty: 0,
      displayMin: true,
      time: 16,
      align: "top",
    },
    {
      start: "Épinay-sur-Seine",
      end: "↑ Saint-Gratien",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "Pont d’Argenteuil",
      end: "↑ Saint-Gratien",
      difficulty: -1,
      displayMin: true,
      time: 20,
      times: { hard: 21, easy: 19},
      align: "top",
    },
    {
      start: "La Villette",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 20,
      align: "top",
    },
    {
      start: "Mairie de La Courneuve",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Mairie de La Courneuve",
      end: "Mairie de Drancy",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "Mairie d’Aubervilliers",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Mairie de Bobigny",
      end: "Mairie de La Courneuve",
      difficulty: 0,
      displayMin: true,
      time: 16,
      align: "top",
    },
    {
      start: "Parc de La Courneuve",
      end: "Mairie de La Courneuve",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Parc de La Courneuve",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "↑ Gonesse",
      end: "Le Bourget",
      difficulty: -1,
      displayMin: true,
      time: 30,
      times: {hard: 32, easy: 28},
      align: "top",
    },
    {
      start: "Parc de La Courneuve",
      end: "Le Bourget",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "La Villette",
      end: "Le Bourget",
      difficulty: 0,
      displayMin: true,
      time: 21,
      align: "top",
    },
    {
      start: "Mairie de Drancy",
      end: "Le Bourget",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Mairie d’Aubervilliers",
      end: "Mairie de La Courneuve",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Mairie d’Aubervilliers",
      end: "Mairie de Pantin",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Mairie d’Aubervilliers",
      end: "Porte de la Chapelle",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Villeneuve-la-Garenne",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Villeneuve-la-Garenne",
      end: "Mairie de Gennevilliers",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
    {
      start: "Colombes",
      end: "Mairie de Gennevilliers",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "Colombes",
      end: "Pont d’Argenteuil",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Bezons",
      end: "Petit Colombes – Quatre Chemins",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Bezons",
      end: "Carrières-sur-Seine",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "← Chatou",
      end: "Carrières-sur-Seine",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Colombes",
      end: "Petit Colombes – Quatre Chemins",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "La Garenne-Colombes",
      end: "Petit Colombes – Quatre Chemins",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Bezons",
      end: "Pont d’Argenteuil",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Centre hospitalier d’Argenteuil",
      end: "Pont d’Argenteuil",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Pont d’Argenteuil",
      end: "Mairie de Gennevilliers",
      difficulty: 0,
      displayMin: true,
      time: 16,
      align: "top",
    },
    {
      start: "Mairie d’Asnières",
      end: "Mairie de Gennevilliers",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Carrefour des Bourguignons",
      end: "Mairie d’Asnières",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Colombes",
      end: "Carrefour des Bourguignons",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Mairie de Gennevilliers",
      end: "Carrefour des Bourguignons",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Gare de Bécon-les-Bruyères",
      end: "Carrefour des Bourguignons",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "La Plaine Saint-Denis",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Porte de la Chapelle",
      end: "La Plaine Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Mairie de Saint-Ouen",
      end: "Porte de la Chapelle",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "bottom",
    },
    {
      start: "Mairie de Saint-Ouen",
      end: "La Plaine Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "bottom",
    },
    {
      start: "Mairie d’Aubervilliers",
      end: "La Plaine Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "bottom",
    },
    {
      start: "Porte de Clichy",
      end: "Mairie de Clichy",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "bottom",
    },
    {
      start: "Mairie d’Asnières",
      end: "Mairie de Clichy",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Mairie de Clichy",
      end: "Saint-Ouen RER",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Porte de Clichy",
      end: "Saint-Ouen RER",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Mairie de Saint-Ouen",
      end: "Saint-Ouen RER",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Mairie de Saint-Ouen",
      end: "Saint-Denis",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Mairie de Saint-Ouen",
      end: "Porte de Saint-Ouen",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Porte de Bercy",
      end: "Pont de Charenton",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Créteil – Palais des Sports",
      end: "Mairie de Maisons-Alfort",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Pont de Joinville",
      end: "Mairie de Maisons-Alfort",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Pont de Joinville",
      end: "Hôpital Henri-Mondor",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "Pont de Charenton",
      end: "Alfortville",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Mairie de Maisons-Alfort",
      end: "Pont de Charenton",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Hôpital Henri-Mondor",
      end: "Pont de Charenton",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Hôpital Henri-Mondor",
      end: "Mairie de Maisons-Alfort",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Alfortville",
      end: "Mairie de Maisons-Alfort",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "bottom",
    },
    {
      start: "Porte Dorée",
      end: "Pont de Charenton",
      difficulty: -1,
      displayMin: true,
      time: 7,
      times: { hard: 9, easy: 6 },
      align: null,
    },
    {
      start: "Pont de Joinville",
      end: "Pont de Charenton",
      difficulty: 0,
      displayMin: true,
      time: 16,
      align: "top",
    },
    {
      start: "Pont de Joinville",
      end: "Château de Vincennes",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "Pont de Joinville",
      end: "Mairie de Nogent-sur-Marne",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Château de Vincennes",
      end: "Mairie de Nogent-sur-Marne",
      difficulty: 0,
      displayMin: true,
      time: 20,
      align: "top",
    },
    {
      start: "Château de Vincennes",
      end: "Pont de Charenton",
      difficulty: -1,
      displayMin: true,
      time: 18,
      times: { hard: 19, easy: 17 },
      align: "top",
    },
    {
      start: "Suresnes",
      end: "Hippodrome de Longchamp",
      difficulty: -1,
      displayMin: false,
      time: 8,
      times: { hard: 9, easy: 7 },
      align: "top",
    },
    {
      start: "Suresnes",
      end: "Puteaux",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "La Défense",
      end: "Puteaux",
      difficulty: 0,
      displayMin: false,
      time: 5,
      align: "top",
    },
    {
      start: "Porte Maillot",
      end: "Puteaux",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "Porte Maillot",
      end: "Mairie de Levallois",
      difficulty: 0,
      displayMin: false,
      time: 10,
      align: "top",
    },
    {
      start: "Mairie de Clichy",
      end: "Mairie de Levallois",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "bottom",
    },
    {
      start: "Mairie d’Asnières",
      end: "Mairie de Levallois",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "bottom",
    },
    {
      start: "Porte de Passy",
      end: "Hippodrome de Longchamp",
      difficulty: 1,
      displayMin: true,
      time: 8,
      times: { hard: 9, easy: 7 },
      align: "top",
    },
    {
      start: "Porte de Passy",
      end: "Maison de la Radio",
      difficulty: -1,
      displayMin: false,
      time: 7,
      times: { hard: 8, easy: 6 },
      align: "top",
    },
    {
      start: "Gare de Bécon-les-Bruyères",
      end: "Mairie d’Asnières",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Gare de Bécon-les-Bruyères",
      end: "Mairie de Levallois",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Mairie de Gennevilliers",
      end: "Mairie de Saint-Ouen",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "La Garenne-Colombes",
      end: "Colombes",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Mairie de Nanterre",
      end: "La Défense",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
    {
      start: "La Garenne-Colombes",
      end: "Mairie de Nanterre",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
    {
      start: "La Garenne-Colombes",
      end: "La Défense",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Puteaux",
      end: "Mairie de Nanterre",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "bottom",
    },
    {
      start: "Suresnes",
      end: "Mairie de Nanterre",
      difficulty: 1,
      displayMin: true,
      time: 15,
      times: { hard: 16, easy: 14 },
      align: "bottom",
    },
    {
      start: "Rueil-Malmaison",
      end: "Mairie de Nanterre",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "← Chatou",
      end: "Mairie de Nanterre",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "← Chatou",
      end: "Rueil-Malmaison",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "bottom",
    },
    {
      start: "Mont Valérien",
      end: "Rueil-Malmaison",
      difficulty: 1,
      displayMin: true,
      time: 20,
      times: { hard: 25, easy: 13 },
      align: "top",
    },
    {
      start: "Suresnes",
      end: "Mont Valérien",
      difficulty: -1,
      displayMin: false,
      time: 12,
      times: { hard: 14, easy: 9 },
      align: "top",
    },
    {
      start: "La Garenne-Colombes",
      end: "Gare de Bécon-les-Bruyères",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "La Garenne-Colombes",
      end: "Gare de Bécon-les-Bruyères",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "La Défense",
      end: "Gare de Bécon-les-Bruyères",
      difficulty: 0,
      displayMin: true,
      time: 15,
      align: "top",
    },
    {
      start: "Colombes",
      end: "Gare de Bécon-les-Bruyères",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Vitry-sur-Seine",
      end: "Ivry-sur-Seine",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Vitry-sur-Seine",
      end: "Mairie de Maisons-Alfort",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Vitry-sur-Seine",
      end: "Villejuif",
      difficulty: -1,
      displayMin: true,
      time: 13,
      times: { hard: 15, easy: 11 },
      align: "top",
    },
    {
      start: "Arcueil",
      end: "Villejuif",
      difficulty: 1,
      displayMin: true,
      time: 12,
      times: { hard: 14, easy: 10 },
      align: "top",
    },
    {
      start: "Pont de Charenton",
      end: "Ivry-sur-Seine",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
    {
      start: "Issy – Val-de-Seine",
      end: "Résistance — Île Saint-Germain",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Issy – Val-de-Seine",
      end: "Porte de Versailles",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
    {
      start: "Issy – Val-de-Seine",
      end: "Hôpital Corentin-Celton",
      difficulty: 0,
      displayMin: false,
      time: 6,
      times: { hard: 7, easy: 5 },
      align: "top",
    },
    {
      start: "Résistance — Île Saint-Germain",
      end: "Hôpital Corentin-Celton",
      difficulty: 0,
      displayMin: false,
      time: 11,
      align: "top",
    },
    {
      start: "Résistance — Île Saint-Germain",
      end: "Meudon",
      difficulty: 1,
      displayMin: false,
      time: 10,
      times: { hard: 12, easy: 7 },
      align: "top",
    },
    {
      start: "Observatoire de Paris",
      end: "Meudon",
      difficulty: 1,
      displayMin: false,
      time: 8,
      times: { hard: 10, easy: 6 },
      align: "top",
    },
    {
      start: "Observatoire de Paris",
      end: "Clamart",
      difficulty: -1,
      displayMin: false,
      time: 18,
      times: { hard: 20, easy: 16 },
      align: "top",
    },
    {
      start: "Observatoire de Paris",
      end: "Mairie de Sèvres",
      difficulty: 1,
      displayMin: true,
      time: 15,
      times: { hard: 20, easy: 14 },
      align: "top",
    },
    {
      start: "Résistance — Île Saint-Germain",
      end: "Clamart",
      difficulty: 1,
      displayMin: true,
      time: 16,
      times: { hard: 17, easy: 14 },
      align: "top",
    },
    {
      start: "↓ Le Plessis-Robinson",
      end: "Clamart",
      difficulty: 1,
      displayMin: false,
      time: 19,
      times: { hard: 21, easy: 17 },
      align: "top",
    },
    {
      start: "Pont de Sèvres",
      end: "Meudon",
      difficulty: 1,
      displayMin: false,
      time: 13,
      times: { hard: 14, easy: 12 },
      align: "top",
    },
    {
      start: "Clamart",
      end: "Meudon",
      difficulty: 0,
      displayMin: true,
      time: 16,
      times: { hard: 14, easy: 12 },
      align: "top",
    },
    {
      start: "Résistance — Île Saint-Germain",
      end: "Marcel Sembat",
      difficulty: 0,
      displayMin: false,
      time: 6,
      align: "top",
    },
  ],
  points: {
    Convention: { x: 476, y: 697 },
    "Croix de Chavaux": { x: 993, y: 582 },
    "Gare Montparnasse": { x: 562, y: 654 },
    "Gare Saint-Lazare": { x: 580, y: 467 },
    "Gare de Lyon": { x: 775, y: 646 },
    "Gare du Nord": { x: 693, y: 471 },
    Invalides: { x: 534, y: 583 },
    "Saint-Michel – Saint-Germain": {x: 647, y: 618},
    "La Villette": { x: 813, y: 372 },
    "Maison de la Radio": { x: 405, y: 612 },
    Montmartre: { x: 634, y: 424 },
    Nation: { x: 841, y: 634 },
    "Les Halles – Rivoli": {x: 663, y: 566},
    "Belleville – Pyrénées": { x: 809, y: 481 },
    "Denfert-Rochereau": { x: 607, y: 714 },
    "Bastille": { x: 742, y: 606 },
    "Place de la Concorde": { x: 567, y: 535 },
    "République": { x: 724, y: 524 },
    "Voltaire":  {x: 793, y: 586},
    "Place de l’Étoile": { x: 471, y: 493 },
    "Place d’Italie": { x: 695, y: 732 },
    "Porte Dorée": { x: 885, y: 706 },
    "Porte Maillot": { x: 417, y: 465 },
    "Porte de Bagnolet": { x: 891, y: 544 },
    "Porte de Bercy": { x: 826, y: 743 },
    "Porte de Clichy": { x: 535, y: 372 },
    "Porte de Saint-Cloud": { x: 339, y: 685 },
    "Porte de la Chapelle": { x: 708, y: 351 },
    "Porte des Lilas": { x: 887, y: 468 },
    "Porte d’Orléans": { x: 580, y: 775 },
    "Père Lachaise": { x: 810, y: 551 },
    "Tour Eiffel": { x: 471, y: 582 },
    "Saint-Denis": { x: 700, y: 142 },
    "Villeneuve-la-Garenne": { x: 599, y: 138 },
    "Mairie de Saint-Ouen": { x: 617, y: 268 },
    "Porte de Saint-Ouen": { x: 597, y: 356 },
    "Pont de Charenton": { x: 934, y: 813 },
    "Porte d’Italie": { x: 710, y: 796 },
    Villejuif: { x: 721, y: 947 },
    "La Défense": { x: 278, y: 398 },
    "Mairie de Clichy": { x: 512, y: 333 },
    "Saint-Ouen RER": { x: 568, y: 315 },
    "Mairie d’Asnières": { x: 462, y: 285 },
    "La Plaine Saint-Denis": { x: 703, y: 255 },
    "Place de l’Alma": { x: 491, y: 536 },
    "Marcel Sembat": { x: 280, y: 718 },
    "Hôpital Corentin-Celton": { x: 412, y: 763 },
    "Porte de Versailles": { x: 446, y: 722 },
    "Mairie de Vanves": { x: 452, y: 795 },
    "Mairie des Lilas": { x: 926, y: 453 },
    "Mairie de Romainville": { x: 997, y: 420 },
    "Mairie de Fontenay-sous-Bois": { x: 1123, y: 638 },
    "Hôpital André-Grégoire – La Boissière": { x: 1057, y: 472 },
    "Mairie de Rosny": { x: 1172, y: 491 },
    "Murs à Pêches – Les Ruffins": { x: 1105, y: 552 },
    "Mairie de Nogent-sur-Marne": { x: 1196, y: 686 },
    "Pont de Joinville": { x: 1116, y: 791 },
    "Val de Fontenay": { x: 1205, y: 613 },
    "Mairie de Pantin": { x: 879, y: 358 },
    "Mairie de Bobigny": { x: 1017, y: 312 },
    "Gare de Bondy": { x: 1137, y: 366 },
    "Noisy-le-Sec": { x: 1052, y: 386 },
    "Bobigny – Pantin – Raymond Queneau": { x: 953, y: 369 },
    "Mairie de Drancy": { x: 1023, y: 209 },
    "Hôpital Jean-Verdier": { x: 1191, y: 280 },
    Bourse: { x: 645, y: 530 },
    "Hippodrome de Longchamp": { x: 264, y: 546 },
    Suresnes: { x: 203, y: 521 },
    "Porte de Passy": { x: 357, y: 584 },
    Puteaux: { x: 254, y: 432 },
    "Mairie de Levallois": { x: 444, y: 379 },
    "Gare de Bécon-les-Bruyères": { x: 380, y: 317 },
    "La Garenne-Colombes": { x: 294, y: 304 },
    Colombes: { x: 316, y: 209 },
    "Mairie de Gennevilliers": { x: 473, y: 183 },
    "Mairie d’Aubervilliers": { x: 791, y: 257 },
    "Parc de La Courneuve": { x: 846, y: 133 },
    "Mairie de La Courneuve": { x: 826, y: 189 },
    "Le Bourget": { x: 963, y: 105 },
    "Carrefour des Bourguignons": { x: 417, y: 238 },
    "Mairie de Saint-Cloud": { x: 189, y: 662 },
    "Château de Vincennes": { x: 984, y: 658 },
    "Créteil – Palais des Sports": { x: 1014, y: 968 },
    "Hôpital Henri-Mondor": { x: 1040, y: 905 },
    "Mairie de Maisons-Alfort": { x: 972, y: 889 },
    "Alfortville": { x: 928, y: 868 },
    "Ivry-sur-Seine": { x: 797, y: 848 },
    "Vitry-sur-Seine": { x: 815, y: 970 },
    "CHU du Kremlin-Bicêtre": { x: 675, y: 830 },
    "Arcueil": { x: 614, y: 882 },
    "Cachan": { x: 611, y: 945 },
    "Bagneux": { x: 531, y: 935 },
    "Châtillon Montrouge": { x: 494, y: 841 },
    "↓ Fontenay-aux-Roses": { x: 474, y: 968 },
    "Issy – Val-de-Seine": { x: 348, y: 736 },
    "Résistance — Île Saint-Germain": { x: 308, y: 780 },
    "Pont de Sèvres": { x: 221, y: 746 },
    "Meudon": { x: 262, y: 815 },
    "Clamart": { x: 336, y: 902 },
    "Mairie de Châtillon": { x: 445, y: 905 },
    "↓ Le Plessis-Robinson": { x: 348, y: 968 },
    "Chaville": { x: 84, y: 832 },
    "Viroflay": { x: 9, y: 874 },
    "Mairie de Sèvres": { x: 171, y: 759 },
    "↓ Vélizy-Villacoublay": { x: 46, y: 968 },
    "Observatoire de Paris": { x: 246, y: 854 },
    "Pont d’Argenteuil": {x: 322, y: 115},
    "Centre hospitalier d’Argenteuil": {x: 233, y: 65},
    "Bezons": {x: 178, y: 199},
    "Petit Colombes – Quatre Chemins": {x: 221, y: 259},
    "Mairie de Nanterre": {x: 147, y: 391},
    "← Chatou": {x: 4, y: 412},
    "Rueil-Malmaison": {x: 39, y: 469},
    "Carrières-sur-Seine": {x: 37, y: 307},
    "Mont Valérien": {x: 153, y: 484},
    "Épinay-sur-Seine": {x: 553, y: 55},
    "↑ Saint-Gratien": {x: 444, y: 28},
    "Villetaneuse": {x: 654, y: 28},
    "Stains": {x: 794, y: 32},
    "Le Blanc-Mesnil": {x: 1099, y: 118},
    "Mairie d’Aulnay-sous-Bois": {x: 1194, y: 155},
    "Villepinte ↗": {x: 1272, y: 28},
    "↑ Gonesse": {x: 1024, y: 28},
    "Villemomble": {x: 1244, y: 440},
    "Neuilly-Plaisance →": { x: 1272, y: 576 },
    "Le Perreux-sur-Marne": { x: 1272, y: 672 },
    "Bry-sur-Marne →": { x: 1272, y: 710 },
    "Mairie de Champigny-sur-Marne": {x: 1267, y: 830},
  },
};